version: "3.7"

services:
  bot:
    build:
      context: oneplusbot
    image: ${REGISTRY_PREFIX}oneplus_bot:${VERSION:-latest}
  database:
    build:
      context: database
      args:
        POSTGRES_VERSION: ${POSTGRES_VERSION}
    image: ${REGISTRY_PREFIX}oneplus_bot_database:${VERSION:-latest}
  pg_admin:
    build:
      context: pgAdmin
      args:
        PG_ADMIN_VERSION: ${PG_ADMIN_VERSION}
    image: ${REGISTRY_PREFIX}oneplus_bot_pg_admin:${VERSION:-latest}
  deployment_container:
    build:
      context: deployment
      args:
        ABSTRACTO_REGISTRY_PREFIX: ${ABSTRACTO_REGISTRY_PREFIX}
        ABSTRACTO_VERSION: ${ABSTRACTO_VERSION}
    image: ${REGISTRY_PREFIX}oneplus_bot_deployment:${VERSION:-latest}
  prometheus:
    build:
      context: prometheus
      args:
        PROMETHEUS_VERSION: ${PROMETHEUS_VERSION}
    image: ${REGISTRY_PREFIX}oneplus_bot_prometheus:${VERSION:-latest}
  grafana:
    build:
      context: grafana
      args:
        GRAFANA_VERSION: ${GRAFANA_VERSION}
    image: ${REGISTRY_PREFIX}oneplus_bot_grafana:${VERSION:-latest}
  promtail:
    build:
      context: promtail
      args:
        PROMTAIL_VERSION: ${PROMTAIL_VERSION}
    image: ${REGISTRY_PREFIX}oneplus_bot_promtail:${VERSION:-latest}
  loki:
    build:
      context: loki
      args:
        LOKI_VERSION: ${LOKI_VERSION}
    image: ${REGISTRY_PREFIX}oneplus_bot_loki:${VERSION:-latest}
