apiVersion: 1
datasources:
  -  access: 'proxy'
     editable: true
     is_default: true
     name: 'prometheus'
     org_id: 1
     type: 'prometheus'
     url: 'http://${PROMETHEUS_HOST}:${PROMETHEUS_PORT}'
     version: 1
  - name: 'postgres-db'
    type: postgres
    access: 'proxy'
    url: '${DB_HOST}:${DB_PORT}'
    password: '${DB_PASS}'
    user: '${DB_USER}'
    database: '${DB_NAME}'
    basicAuth: false
    is_default: false
    jsonData:
       sslmode: 'disable'
    version: 1
    editable: false
  - name: Loki
    type: loki
    access: proxy
    url: 'http://${LOKI_HOST}:${LOKI_PORT}'
    jsonData:
      maxLines: 2000