version: '3.7'

services:
  db:
    image: ${REGISTRY_PREFIX}oneplus_bot_database:${ONEPLUS_BOT_VERSION}
    container_name: database
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
    ports:
      - "127.0.0.1:${DATABASE_PORT}:5432"
    networks:
      - oneplusbot
    volumes:
      - db-data:/var/lib/postgresql/data
  deployment_container:
    container_name: deployment
    image: ${REGISTRY_PREFIX}oneplus_bot_deployment:${ONEPLUS_BOT_VERSION}
    depends_on:
      - db
    environment:
      DB_PASS: ${DATABASE_PASSWORD}
      DB_HOST: ${DATABASE_HOST}
      DB_PORT: ${DATABASE_PORT}
      DB_USER: ${DATABASE_USER}
      DB_NAME: ${DATABASE_NAME}
      EXECUTE_DEPLOYMENT: ${EXECUTE_DEPLOYMENT}
      EXECUTE_LIQUIBASE: ${EXECUTE_LIQUIBASE}
      EXECUTE_TEMPLATES: ${EXECUTE_TEMPLATES}
      LIQUIBASE_PATH: ${LIQUIBASE_PATH:-/liquibase}
      POSTGRES_DRIVER_PATH: ${EXECUTE_DEPLOYMENT:-/postgres/driver.jar}
      WAIT_HOSTS: database:5432
    networks:
      - oneplusbot
  bot:
    image: ${REGISTRY_PREFIX}oneplus_bot:${ONEPLUS_BOT_VERSION}
    depends_on:
      - db
      - deployment_container
    restart: on-failure
    container_name: oneplusbot
    environment:
      TOKEN: ${TOKEN}
      REMOTE_DEBUG: ${REMOTE_DEBUG}
      DB_PASS: ${DATABASE_PASSWORD}
      DB_HOST: ${DATABASE_HOST}
      DB_PORT: ${DATABASE_PORT}
      DB_USER: ${DATABASE_USER}
      DB_NAME: ${DATABASE_NAME}
      REST_USER_NAME: ${REST_USER_NAME}
      REST_PASSWORD: ${REST_PASSWORD}
      YOUTUBE_API_KEY: ${YOUTUBE_API_KEY}
    command: sh -c "while ping -c1 deployment_container &>/dev/null; do sleep 1; done; echo 'Liquibase finished!' && ./start.sh"
    ports:
      - "127.0.0.1:${DEBUG_PORT}:5005"
      - "127.0.0.1:${TOMCAT_PORT}:8080"
    networks:
      - oneplusbot
    volumes:
      - bot-logs:/logs
      - ./config:/config
  pgadmin:
    container_name: pgadmin
    image: ${REGISTRY_PREFIX}oneplus_bot_pg_admin:${ONEPLUS_BOT_VERSION}
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "127.0.0.1:${PGADMIN_PORT}:80"
    restart: unless-stopped
    networks:
      - oneplusbot
  prometheus:
    container_name: prometheus
    image: ${REGISTRY_PREFIX}oneplus_bot_prometheus:${ONEPLUS_BOT_VERSION}
    depends_on:
      - bot
    ports:
      - "127.0.0.1:${PROMETHEUS_PORT}:9090"
    restart: unless-stopped
    networks:
      - oneplusbot
    volumes:
      - ./res/prometheus-scrapper-password-filled:/etc/prometheus/micrometer_password
      - prometheus-data:/prometheus
  grafana:
    container_name: grafana
    image: ${REGISTRY_PREFIX}oneplus_bot_grafana:${ONEPLUS_BOT_VERSION}
    depends_on:
      - prometheus
      - bot
    ports:
      - "127.0.0.1:${GRAFANA_PORT}:3000"
    restart: unless-stopped
    volumes:
      - grafana-user-data:/var/lib/grafana
    networks:
      - oneplusbot

networks:
  oneplusbot:
    driver: bridge
    name: oneplusbot-network

volumes:
  db-data:
  grafana-user-data:
  prometheus-data:
  bot-logs: