global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 1m
scrape_configs:
  - job_name: oneplus_bot_micrometer
    honor_timestamps: true
    scrape_interval: 5s
    scrape_timeout: 5s
    metrics_path: /actuator/prometheus
    scheme: http
    static_configs:
      - targets:
          - 172.17.0.1:8080
    basic_auth:
      username: "abstracto"
      password_file: /etc/prometheus/micrometer_password