FROM docker.pkg.github.com/sheldan/abstracto/abstracto_deployment:latest
MAINTAINER Sheldan
ADD template-artifacts /templates
ADD translation-artifacts /translations
ADD liquibase-artifacts /liquibase-zips
ADD config /
