apiVersion: v1
kind: Secret
metadata:
  name: api-keys
data:
  discordToken: {{ $.Values.apiKeys.discord.token | b64enc }} # b64enc is needed, because a stringData secret field cannot hold numeric values
  youtubeApiKey: {{ $.Values.apiKeys.youtube.apiKey | b64enc }}