apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  annotations:
    "helm.sh/hook": pre-upgrade,pre-install
    "helm.sh/hook-weight": "-6"
data:
  dbPassword: {{ $.Values.dbCredentials.password | b64enc }} # b64enc is needed, because a stringData secret field cannot hold numeric values
  dbUser: {{ $.Values.dbCredentials.userName | b64enc }}
  dbHost: {{ $.Values.dbCredentials.host | b64enc }}
  dbPort: {{ $.Values.dbCredentials.port | b64enc }}
  dbName: {{ $.Values.dbCredentials.name | b64enc }}