{
 "title": "OnePlus Bot Logs",
 "description": "Overview over logging outputs of OnePlusBot",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "logFilter" }
  ]
 },
 "panels": [
  {
   "title": "OnePlusBot Logs",
   "type": "logs",
   "description": "Display logs and search for logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{app=\"oneplus-bot\", namespace=\"oneplus-bot\"} |= `$logFilter`",
     "maxLines": 5000
    }
   ]
  },
  {
   "title": "OnePlusBot Error Logs",
   "type": "logs",
   "description": "Any line on level ERROR",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "{app=\"oneplus-bot\", namespace=\"oneplus-bot\"} |= \"ERROR\"",
     "maxLines": 5000
    }
   ]
  },
  {
   "title": "Log Rate",
   "type": "timeseries",
   "description": "Number of log events",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "rate({app=\"oneplus-bot\", namespace=\"oneplus-bot\"}[$__interval])"
    }
   ]
  }
 ]
}