{
 "title": "OnePlusBot stats",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Core", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Users",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(1)\nFROM\n  abstracto.auser\n\n"
    }
   ]
  },
  {
   "title": "Users In Servers",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(1)\nFROM\n  abstracto.user_in_server\n\n"
    }
   ]
  },
  {
   "title": "Commands",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(1)\nFROM\n  abstracto.command\n\n"
    }
   ]
  },
  {
   "title": "Templates",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(1)\nFROM\n  abstracto.template\n\n"
    }
   ]
  },
  {
   "title": "Channels",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(1) as existing\nFROM\n  abstracto.channel\nWHERE \ndeleted = false\n"
    },
    {
     "rawSql": "SELECT\n  count(1) as deleted\nFROM\n  abstracto.channel\nWHERE \ndeleted = true\n"
    }
   ]
  },
  {
   "title": "Roles",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(1) as existing\nFROM\n  abstracto.role\nwhere\ndeleted = false\n"
    },
    {
     "rawSql": "SELECT\n  count(1) as deleted\nFROM\n  abstracto.role\nwhere\ndeleted = true"
    }
   ]
  },
  {
   "title": "Channel groups",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(1)\nFROM\n  abstracto.channel_group\n\n"
    }
   ]
  },
  {
   "title": "Posttargets",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(1)\nFROM\n  abstracto.posttarget\n\n"
    }
   ]
  },
  {
   "title": "Profanity config",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(1) as group\nFROM\n  abstracto.profanity_group\n\n"
    },
    {
     "rawSql": "SELECT\n  count(1) as regex\nFROM\n  abstracto.profanity_regex\n\n"
    }
   ]
  },
  {
   "title": "Configured Emotes",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(1)\nFROM\n  abstracto.emote\n\n"
    }
   ]
  },
  {
   "title": "Channel in channel groups",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(1)\nFROM\n  abstracto.channel_in_group\n\n"
    }
   ]
  },
  {
   "title": "Scheduled triggers",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(1)\nFROM\n  abstracto.qrtz_simple_triggers\n\n"
    }
   ]
  },
  {
   "title": "Custom templates",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(1)\nFROM\n  abstracto.custom_template\n\n"
    }
   ]
  },
  {
   "title": "Components",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(1) AS \"Buttons\"\n  \nFROM abstracto.component_payload\nWHERE type = 'BUTTON'"
    },
    {
     "rawSql": "SELECT\n  count(1) AS \"Selections\"\n  \nFROM abstracto.component_payload\nWHERE type = 'SELECTION'"
    }
   ]
  },
  { "title": "Moderation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Warnings",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(1) as \"Decayed\"\nFROM\n  abstracto.warning\nWHERE decayed = true\n"
    },
    {
     "rawSql": "SELECT\n  count(1) as \"Active\"\nFROM\n  abstracto.warning\nWHERE decayed = false\n"
    }
   ]
  },
  {
   "title": "User notes",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(1)\nFROM\n  abstracto.user_note\n\n"
    }
   ]
  },
  {
   "title": "Mutes",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(1) as \"Active\"\nFROM\n  abstracto.mute\nWHERE mute_ended = false"
    },
    {
     "rawSql": "SELECT\n  count(1) as \"Ended\"\nFROM\n  abstracto.mute\nWHERE mute_ended = true"
    }
   ]
  },
  {
   "title": "Filtered invites",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(1)\nFROM\n  abstracto.filtered_invite_link\n\n"
    }
   ]
  },
  {
   "title": "Reaction reports",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(1)\nFROM\n  abstracto.reaction_report\n\n"
    }
   ]
  },
  {
   "title": "Profanity used",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(1)\nFROM\n  abstracto.profanity_use\n\n"
    }
   ]
  },
  {
   "title": "Profanity verified",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 17, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(1)\nFROM\n  abstracto.profanity_use\nWHERE \n  verified = true\n"
    }
   ]
  },
  {
   "title": "Profanity confirmed",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 20, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(1)\nFROM\n  abstracto.profanity_use\nWHERE \n  confirmed = true\n\n"
    }
   ]
  },
  { "title": "Starboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Starboard posts",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(1)\nFROM\n  abstracto.starboard_post\n\n"
    }
   ]
  },
  {
   "title": "Given stars",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(1)\nFROM\n  abstracto.starboard_post_reaction\n\n"
    }
   ]
  },
  {
   "title": "Starred users",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with starred_users as (\nSELECT\n  count(1) as count\nFROM\n  abstracto.starboard_post\n  GROUP BY author_user_in_server_id\n)\nSELECT count(1) from starred_users"
    }
   ]
  },
  {
   "title": "Starring users",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with starring_users as (\nSELECT\n  count(1) as count\nFROM\n  abstracto.starboard_post_reaction\n  GROUP BY reactor_user_in_server_id\n)\nSELECT count(1) from starring_users"
    }
   ]
  },
  { "title": "Modmail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Modmail threads",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(1)\nFROM\n  abstracto.mod_mail_thread\n\n"
    }
   ]
  },
  {
   "title": "Modmail messages",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(1)\nFROM\n  abstracto.mod_mail_message\n\n"
    }
   ]
  },
  { "title": "Experience details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Users with experience",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(1)\nFROM\n  abstracto.user_experience\n\n"
    }
   ]
  },
  {
   "title": "Experience roles",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 3, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT \n  role_id as \"Role ID\",\n  count(1) as \"Member count\"\nFROM \n  abstracto.user_experience\n  GROUP BY role_id"
    }
   ]
  },
  {
   "title": "Users without experience",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n(\nSELECT\n  count(1)\nFROM\n  abstracto.user_in_server\n)\n-\n(\nSELECT\n  count(1)\nFROM\n  abstracto.user_experience\n)"
    }
   ]
  },
  {
   "title": "Users without role",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  count(1)\nFROM\n abstracto.user_experience\nWHERE role_id IS NULL"
    }
   ]
  },
  {
   "title": "Experience roles",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(1)\nFROM\n  abstracto.experience_role\n\n"
    }
   ]
  },
  { "title": "Emote tracking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Tracked",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(1)\nFROM\n  abstracto.tracked_emote\nWHERE \n  tracking_enabled = true\n\n"
    }
   ]
  },
  {
   "title": "Untracked",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(1)\nFROM\n  abstracto.tracked_emote\nWHERE \n  tracking_enabled = false\n\n"
    }
   ]
  },
  {
   "title": "Deleted Tracked emotes",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(1)\nFROM\n  abstracto.tracked_emote\nWHERE \n  deleted = true\n\n"
    }
   ]
  },
  {
   "title": "Animated Tracked emotes",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(1)\nFROM\n  abstracto.tracked_emote\nWHERE \n  animated = true\n\n"
    }
   ]
  },
  {
   "title": "External Tracked emotes",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(1)\nFROM\n  abstracto.tracked_emote\nWHERE \n  external = true\n\n"
    }
   ]
  },
  {
   "title": "Emote usage today",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(1)\nFROM\n  abstracto.used_emote\nWHERE \n  use_date = CURRENT_DATE\n\n"
    }
   ]
  },
  {
   "title": "Emote usage last week",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(1)\nFROM\n  abstracto.used_emote\nWHERE \n  use_date > CURRENT_DATE - 7\n\n"
    }
   ]
  },
  {
   "title": "Total emote usage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  sum(amount)\nFROM\n  abstracto.used_Emote\n\n\n"
    }
   ]
  },
  {
   "title": "Max emote usage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  max(amount)\nFROM\n  abstracto.used_Emote\n\n\n"
    }
   ]
  },
  {
   "title": "Assignable roles",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Assignable roles",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  count(1)\nFROM\n  abstracto.assignable_role\n\n"
      }
     ]
    },
    {
     "title": "Assigned roles",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  count(1)\nFROM\n  abstracto.assigned_role_in_user\n\n"
      }
     ]
    },
    {
     "title": "Assignable role places",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 6, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  count(1)\nFROM\n  abstracto.assignable_role_place\n\n"
      }
     ]
    }
   ]
  },
  {
   "title": "OnePlus Bot custom",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tracked news posts",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  count(1)\nFROM\n  abstracto.news_post\n\n"
      }
     ]
    },
    {
     "title": "FAQ usages",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  sum(uses)\nFROM\n  abstracto.faq_channel_group_command\n\n"
      }
     ]
    },
    {
     "title": "FAQ commands",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 6, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  count(1)\nFROM\n  abstracto.faq_command\n\n"
      }
     ]
    },
    {
     "title": "FAQ responses",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 9, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  count(1)\nFROM\n  abstracto.faq_command_response\n\n"
      }
     ]
    },
    {
     "title": "FAQ channel groups",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 12, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  count(1)\nFROM\n  abstracto.faq_channel_group\n\n"
      }
     ]
    },
    {
     "title": "Referral users",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 15, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  count(1)\nFROM\n  abstracto.referral_user_in_server\n\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Various",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Embedded messages",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  count(1)\nFROM\n  abstracto.embedded_message\n\n"
      }
     ]
    },
    {
     "title": "Active reminders",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  count(1)\nFROM\n  abstracto.reminder\nWHERE \n  reminded = false\n"
      }
     ]
    },
    {
     "title": "Past reminders",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 6, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  count(1)\nFROM\n  abstracto.reminder\nWHERE \n  reminded = true\n"
      }
     ]
    },
    {
     "title": "Suggestions",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 9, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  count(1)\nFROM\n  abstracto.suggestion\n\n"
      }
     ]
    }
   ]
  }
 ]
}