{
 "title": "OnePlus Bot status",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "application", "query": "oneplus-bot" }
  ]
 },
 "panels": [
  {
   "title": "Discord API Interaction",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(discord_api_interactions_total[1m])",
     "legendFormat": "{{ action }}"
    }
   ]
  },
  {
   "title": "Commands processed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(command_processed_total[1m])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Message events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "increase(message_total[1m])", "legendFormat": "{{ action }}" }
   ]
  },
  {
   "title": "HTTP Reponse codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(okhttp_request_total[1m])",
     "legendFormat": "{{ http_code }}"
    }
   ]
  },
  {
   "title": "Cache statistic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(cache_evictions_total{application=\"$application\", cache=\"messages\"}[1m])",
     "legendFormat": "Cache evictions"
    },
    {
     "expr": "increase(cache_gets_total{application=\"$application\", cache=\"messages\"}[1m])",
     "legendFormat": "Cache gets {{ result }}"
    },
    {
     "expr": "increase(cache_puts_total{application=\"$application\", cache=\"messages\"}[1m])",
     "legendFormat": "Cache puts"
    },
    {
     "expr": "increase(cache_removals{application=\"$application\", cache=\"messages\"}[1m])",
     "legendFormat": "Cache  removals"
    }
   ]
  },
  {
   "title": "Gateway ping",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "discord_gateway_ping", "legendFormat": "Gateway ping" }
   ]
  },
  {
   "title": "Starboard reactions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(starboard_stars_total[1m])",
     "legendFormat": "{{ action }}"
    }
   ]
  },
  {
   "title": "Emote tracking",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(emote_usages_total[1m])",
     "legendFormat": "Used emotes"
    }
   ]
  },
  {
   "title": "Experience storage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(experience_runtime_storage[1m])",
     "legendFormat": "Amount of entries"
    }
   ]
  },
  {
   "title": "Assignable role actions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(assignable_roles_total[1m])",
     "legendFormat": "{{ action }}"
    }
   ]
  },
  {
   "title": "JDA Events",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "increase(jda_event_total[1m])", "legendFormat": "{{ event_class }}" }
   ]
  }
 ]
}