name: Publish package to GitHub Packages
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Set up Java for publishing to GitHub Packages
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17
      - name: Load current version
        id: version
        run: echo "version=$(mvn -s settings.xml --file pom.xml -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_ENV
      - name: Publish to GitHub Packages
        run: mvn -s settings.xml --file pom.xml -B deploy -Dmaven.wagon.http.pool=false -DskipTests=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          user: Sheldan
          token: ${{ secrets.ABSTRACTO_PAT }}
      - name: Login to Harbor
          uses: docker/login-action@v2
          with:
            registry: harbor.sheldan.dev
            username: ${{ secrets.HARBOR_USERNAME }}
            password: ${{ secrets.HARBOR_TOKEN }}
      - name: Load env files
        id: dotenv
        uses: falti/dotenv-action@v1.0.4
        with:
          path: ./deployment/image-packaging/src/main/docker
      - name: Push container
        working-directory: ./deployment/image-packaging/src/main/docker
        run: docker-compose build && docker-compose push
        env:
          REGISTRY_PREFIX: ${{ steps.dotenv.outputs.registry_prefix }}
          VERSION: ${{ steps.dotenv.outputs.version }}
      - name: Helm push
        working-directory: ./deployment/helm/
        run: |-
          helm registry login -u ${{ secrets.HARBOR_USERNAME }} -p ${{ secrets.HARBOR_TOKEN }} harbor.sheldan.dev
          helm package oneplus-bot
          helm push oneplus-bot*.tgz oci://harbor.sheldan.dev/oneplus-bot
